name: Build and Publish OpenAPI UI

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ./services/${{ inputs.service }}

    - name: Generate Swagger Metadata
      run: npm run build:metadata
      shell: bash
      working-directory: ./services/${{ inputs.service }}

    - name: Generate OpenAPI/Swagger JSON
      run: npm run build:swagger
      shell: bash
      working-directory: ./services/${{ inputs.service }}

    - name: Generate OpenAPI/Swagger UI
      run: npm run generate-swagger-ui
      shell: bash
      working-directory: ./services/${{ inputs.service }}

    - name: Copy OpenAPI Spec (index.html) to root docs directory
      run: cp ./services/${{ inputs.service }}/docs/index.html ./docs/${{ inputs.service }}/
      shell: bash
