openapi: 3.0.0
paths:
  /api/health:
    get:
      operationId: ApiController_health
      parameters: []
      responses:
        '200':
          description: ''
  /api/resetScanner:
    post:
      operationId: ApiController_resetScanner
      parameters: []
      responses:
        '201':
          description: ''
info:
  title: Content Watcher Service API
  description: Content Watcher Service API
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
      description: Enter JWT token
    cookie:
      type: apiKey
      in: cookie
      name: SESSION
  schemas: {}
  responses: {}